FROM golang:1.17 AS builder
WORKDIR /app

COPY go.mod go.mod
RUN go mod download
COPY . .
RUN swag init

ENV APP_ENV=local_env
RUN GOOS=linux CGO_ENABLED=0 go build -o driverLocation


FROM alpine:latest
WORKDIR /root

RUN mkdir .config

COPY .config/* .config/

COPY --from=builder /app/driverLocation .
CMD ["./driverLocation"]